#!/usr/bin/python
import SocketServer
import tempfile
import subprocess
import os
import json

LOCO_HOST = 'localhost'
LOCO_PORT = 4206
LOCO_FALLBACK_EDITOR = 'gedit'


class LocoServer(SocketServer.TCPServer):
    allow_reuse_address = True


class LocoHandler(SocketServer.BaseRequestHandler):
    def determine_editor(self):
        if os.environ.get('LOCO_EDITOR', None):
            return os.environ['LOCO_EDITOR']
        elif os.environ.get('EDITOR', None):
            return os.environ['EDITOR']
        
        return LOCO_FALLBACK_EDITOR

    def handle(self):
        self.file_contents = self.request.recv(65536)
        self.temp_filename = tempfile.mkstemp()[1]

        with open(self.temp_filename, 'wb') as f:
            f.write(self.file_contents)
            f.flush()
        
        with open('/dev/null', 'rwb') as devnull:
            subprocess.call([self.determine_editor(), self.temp_filename],
                            stdin=devnull,
                            stdout=devnull,
                            stderr=devnull)

        with open(self.temp_filename, 'r') as f:
            self.request.sendall(f.read(65536))


if __name__ == '__main__':
    srv = LocoServer((LOCO_HOST, LOCO_PORT), LocoHandler)
    srv.serve_forever()
